import React, { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import {
  BarChart3,
  TrendingUp,
  Activity,
  Calendar,
  CheckCircle2,
  Users,
  Clock,
  Sparkles
} from 'lucide-react';
import {
  AreaChart,
  Area,
  LineChart,
  Line,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  Legend
} from 'recharts';
import { api } from '../services/api';
import { AnalyticsOverview, AnalyticsSession, Session } from '../types';
import { StatCard } from '../components/StatCard';
import { Badge } from '../components/Badge';

export const AnalyticsPage: React.FC = () => {
  const [searchParams, setSearchParams] = useSearchParams();
  const sessionIdParam = searchParams.get('session_id');

  const [sessions, setSessions] = useState<Session[]>([]);
  const [selectedSessionId, setSelectedSessionId] = useState<number | ''>(
    sessionIdParam ? Number(sessionIdParam) : ''
  );

  const [overview, setOverview] = useState<AnalyticsOverview | null>(null);
  const [sessionAnalytics, setSessionAnalytics] = useState<AnalyticsSession | null>(null);
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    const loadInitial = async () => {
      try {
        setLoading(true);
        const [sessList, ovData] = await Promise.all([
          api.getSessions(),
          api.getAnalyticsOverview()
        ]);
        setSessions(sessList);
        setOverview(ovData);

        if (selectedSessionId) {
          const sData = await api.getSessionAnalytics(Number(selectedSessionId));
          setSessionAnalytics(sData);
        }
      } catch (err) {
        console.error('Failed to load analytics:', err);
      } finally {
        setLoading(false);
      }
    };
    loadInitial();
  }, [selectedSessionId]);

  const handleSessionChange = (idStr: string) => {
    if (idStr) {
      setSelectedSessionId(Number(idStr));
      setSearchParams({ session_id: idStr });
    } else {
      setSelectedSessionId('');
      setSearchParams({});
      setSessionAnalytics(null);
    }
  };

  const PIE_COLORS = ['#10b981', '#f43f5e'];

  return (
    <div>
      {/* Session Filter Bar */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        flexWrap: 'wrap',
        gap: 16,
        marginBottom: 24,
        background: 'var(--bg-surface)',
        padding: '16px 24px',
        borderRadius: 'var(--radius-md)',
        border: '1px solid var(--border-subtle)'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <span style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', fontWeight: 500 }}>
            Scope:
          </span>
          <select
            className="form-select"
            value={selectedSessionId}
            onChange={(e) => handleSessionChange(e.target.value)}
            style={{ minWidth: 260 }}
          >
            <option value="">Global System Overview (All Sessions)</option>
            {sessions.map((s) => (
              <option key={s.id} value={s.id}>
                {s.name} ({s.date})
              </option>
            ))}
          </select>
        </div>

        <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>
          Real-time metrics generated by CV detection and tracking
        </span>
      </div>

      {/* Global Overview Section (when no single session is selected) */}
      {!selectedSessionId && overview && (
        <>
          <div className="stats-grid">
            <StatCard
              label="Enrolled Students"
              value={overview.total_students}
              icon={Users}
              subtext="Registered in database"
              color="var(--accent-primary)"
            />
            <StatCard
              label="Total Sessions"
              value={overview.total_sessions}
              icon={Calendar}
              subtext={`${overview.active_sessions} currently active`}
              color="var(--accent-cyan)"
            />
            <StatCard
              label="Overall Attendance Rate"
              value={`${overview.avg_attendance_rate}%`}
              icon={CheckCircle2}
              subtext="Aggregated across all classes"
              color="var(--accent-emerald)"
            />
            <StatCard
              label="Avg Observable Engagement"
              value={`${Math.round(overview.avg_engagement_score * 100)}%`}
              icon={Activity}
              subtext="CV orientation estimate"
              color="var(--accent-purple)"
            />
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '3fr 2fr', gap: 24, marginBottom: 28 }}>
            {/* Historical Attendance Trends */}
            <div className="glass-panel">
              <div className="panel-header">
                <div className="panel-title">
                  <TrendingUp size={18} color="var(--accent-emerald)" />
                  <span>Session Attendance Comparison</span>
                </div>
              </div>
              <div style={{ height: 280 }}>
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={overview.attendance_trends}>
                    <XAxis dataKey="session_name" stroke="#475569" tick={{ fill: '#94a3b8', fontSize: 11 }} />
                    <YAxis domain={[0, 100]} stroke="#475569" tick={{ fill: '#94a3b8', fontSize: 11 }} tickFormatter={(v) => `${v}%`} />
                    <Tooltip
                      contentStyle={{
                        backgroundColor: '#182030',
                        borderColor: 'rgba(255,255,255,0.1)',
                        borderRadius: 8,
                        color: '#fff'
                      }}
                    />
                    <Bar dataKey="rate" fill="var(--accent-primary)" radius={[4, 4, 0, 0]} name="Attendance Rate %" />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* Engagement Distribution */}
            <div className="glass-panel">
              <div className="panel-header">
                <div className="panel-title">
                  <Sparkles size={18} color="var(--accent-cyan)" />
                  <span>Engagement Distribution</span>
                </div>
              </div>
              <div style={{ height: 280 }}>
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={overview.engagement_distribution} layout="vertical">
                    <XAxis type="number" stroke="#475569" tick={{ fill: '#94a3b8', fontSize: 11 }} />
                    <YAxis dataKey="category" type="category" width={110} stroke="#475569" tick={{ fill: '#94a3b8', fontSize: 10 }} />
                    <Tooltip
                      contentStyle={{
                        backgroundColor: '#182030',
                        borderColor: 'rgba(255,255,255,0.1)',
                        borderRadius: 8,
                        color: '#fff'
                      }}
                    />
                    <Bar dataKey="count" fill="var(--accent-purple)" radius={[0, 4, 4, 0]} name="Observations" />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>
          </div>
        </>
      )}

      {/* Single Session Deep Dive (when session_id is selected) */}
      {selectedSessionId && sessionAnalytics && (
        <>
          <div className="stats-grid">
            <StatCard
              label="Present Students"
              value={sessionAnalytics.present_count}
              icon={CheckCircle2}
              subtext={`Out of ${sessionAnalytics.present_count + sessionAnalytics.absent_count} enrolled`}
              color="var(--accent-emerald)"
            />
            <StatCard
              label="Absent Students"
              value={sessionAnalytics.absent_count}
              icon={Users}
              subtext="Unconfirmed / missed"
              color="var(--accent-rose)"
            />
            <StatCard
              label="Session Attendance Rate"
              value={`${sessionAnalytics.attendance_rate}%`}
              icon={TrendingUp}
              subtext="Confirmed presence"
              color="var(--accent-cyan)"
            />
            <StatCard
              label="Observable Engagement"
              value={`${Math.round(sessionAnalytics.avg_engagement * 100)}%`}
              icon={Activity}
              subtext="Average visual signal"
              color="var(--accent-purple)"
            />
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: 24, marginBottom: 28 }}>
            {/* Timeline Curve */}
            <div className="glass-panel">
              <div className="panel-header">
                <div className="panel-title">
                  <Activity size={18} color="var(--accent-purple)" />
                  <span>Chronological Engagement Timeline</span>
                </div>
                <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>
                  Smoothed EMA score over time
                </span>
              </div>
              <div style={{ height: 260 }}>
                {sessionAnalytics.engagement_timeline.length > 0 ? (
                  <ResponsiveContainer width="100%" height="100%">
                    <LineChart data={sessionAnalytics.engagement_timeline}>
                      <XAxis dataKey="time" stroke="#475569" tick={{ fill: '#94a3b8', fontSize: 11 }} />
                      <YAxis domain={[0, 1]} stroke="#475569" tick={{ fill: '#94a3b8', fontSize: 11 }} tickFormatter={(v) => `${Math.round(v * 100)}%`} />
                      <Tooltip
                        contentStyle={{
                          backgroundColor: '#182030',
                          borderColor: 'rgba(255,255,255,0.1)',
                          borderRadius: 8,
                          color: '#fff'
                        }}
                      />
                      <Line
                        type="monotone"
                        dataKey="engagement"
                        stroke="var(--accent-purple)"
                        strokeWidth={2.5}
                        dot={false}
                        name="Engagement Score"
                      />
                      <Line
                        type="monotone"
                        dataKey="orientation"
                        stroke="var(--accent-cyan)"
                        strokeWidth={1.5}
                        strokeDasharray="3 3"
                        dot={false}
                        name="Orientation Score"
                      />
                    </LineChart>
                  </ResponsiveContainer>
                ) : (
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', color: 'var(--text-muted)' }}>
                    No engagement samples recorded for this session yet.
                  </div>
                )}
              </div>
            </div>

            {/* Attendance Proportion Pie Chart */}
            <div className="glass-panel">
              <div className="panel-header">
                <div className="panel-title">
                  <span>Attendance Ratio</span>
                </div>
              </div>
              <div style={{ height: 260 }}>
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={[
                        { name: 'Present', value: sessionAnalytics.present_count },
                        { name: 'Absent', value: sessionAnalytics.absent_count }
                      ]}
                      innerRadius={60}
                      outerRadius={80}
                      paddingAngle={5}
                      dataKey="value"
                    >
                      {PIE_COLORS.map((color, index) => (
                        <Cell key={`cell-${index}`} fill={color} />
                      ))}
                    </Pie>
                    <Tooltip
                      contentStyle={{
                        backgroundColor: '#182030',
                        borderColor: 'rgba(255,255,255,0.1)',
                        borderRadius: 8,
                        color: '#fff'
                      }}
                    />
                    <Legend wrapperStyle={{ fontSize: 12, color: '#94a3b8' }} />
                  </PieChart>
                </ResponsiveContainer>
              </div>
            </div>
          </div>

          {/* Session Roster Table */}
          <div className="glass-panel" style={{ padding: 0 }}>
            <div style={{ padding: '16px 20px', borderBottom: '1px solid var(--border-subtle)', fontWeight: 600 }}>
              Session Attendance Roster
            </div>
            <div className="table-container" style={{ border: 'none' }}>
              <table className="data-table">
                <thead>
                  <tr>
                    <th>Student ID</th>
                    <th>Name</th>
                    <th>Status</th>
                    <th>First Observed</th>
                    <th>Last Observed</th>
                    <th>Presence Duration</th>
                    <th>Confidence</th>
                  </tr>
                </thead>
                <tbody>
                  {sessionAnalytics.attendance_list.map((r) => (
                    <tr key={r.id}>
                      <td className="font-mono" style={{ color: 'var(--accent-cyan)' }}>{r.student_code}</td>
                      <td style={{ fontWeight: 600 }}>{r.student_name}</td>
                      <td><Badge status={r.status} /></td>
                      <td>{r.first_seen ? new Date(r.first_seen).toLocaleTimeString() : '—'}</td>
                      <td>{r.last_seen ? new Date(r.last_seen).toLocaleTimeString() : '—'}</td>
                      <td>{r.duration_seconds > 0 ? `${Math.round(r.duration_seconds / 60)} min` : '0s'}</td>
                      <td>{r.confidence > 0 ? `${Math.round(r.confidence * 100)}%` : '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </>
      )}
    </div>
  );
};
